"""Generate a clearly synthetic evidence pack for all canonical control contracts.

The pack is intentionally external to the workbench at runtime so the self-scan guard
cannot mistake the workbench's own files for organisational evidence.
"""
from __future__ import annotations
import hashlib
import re
import tempfile
from pathlib import Path
import yaml

ROOT = Path(__file__).resolve().parent
CONTRACT_DIR = ROOT / "governance" / "knowledge" / "contracts"
FRAMEWORK_FILES = {
    "MAS": "mas.yaml",
    "ISO 42001": "iso_42001.yaml",
    "NIST AI RMF": "nist_ai_rmf.yaml",
    "MGF Agentic": "mgf_agentic.yaml",
    "SAFR": "safr.yaml",
}

def _slug(s: str) -> str:
    return re.sub(r"[^A-Za-z0-9._-]+", "_", s).strip("_")[:90]

def _element_fact(control: dict, element: dict, idx: int, scenario: str) -> str:
    text = str(element.get("text", "")).strip()
    # Keep the fact factual and synthetic; never state the rating in evidence.
    if scenario == "partial" and idx == len(control.get("elements", [])) - 1:
        return f"Evidence file reviewed: the artefact set does not contain a record demonstrating: {text}"
    if scenario == "none":
        return f"Reference artefact states an intent related to this area but does not demonstrate: {text}"
    return f"Evidence artefact contains the following controlled fact: {text}"

def _scenario_for(control_id: str) -> str:
    # Deterministic mixture gives the scan something useful to discriminate.
    n = int(hashlib.sha256(control_id.encode()).hexdigest()[:2], 16) % 10
    return "full" if n < 6 else "partial" if n < 9 else "none"

def _mock_doc(framework: str, c: dict, scenario: str) -> str:
    cid = str(c.get("control_id", "")).strip()
    title = str(c.get("title", "")).strip()
    owner = str(c.get("owner", "AI Governance")).strip()
    source = str(c.get("requirement_source", "Internal control standard")).strip()
    elements = c.get("elements") or []
    evs = c.get("expected_evidence") or []
    population = str(c.get("population_and_evidence_floor", "Population and evidence floor defined by the control contract.")).strip()
    lines = [
        "# SYNTHETIC DEMO EVIDENCE — NOT REAL ORGANISATIONAL EVIDENCE",
        "",
        f"Framework: {framework}",
        f"Control ID: {cid}",
        f"Control area: {title}",
        f"Evidence owner: {owner}",
        "As-at date: 2026-09-12",
        "Scenario: " + {"full":"synthetic complete evidence", "partial":"synthetic partial evidence", "none":"synthetic insufficient evidence"}[scenario],
        "",
        "## Evidence register",
    ]
    if evs:
        for x in evs:
            lines.append(f"- Declared artefact: {x}")
    else:
        lines += [
            "- Governance policy or procedure",
            "- Control register / approval record",
            "- Operating sample or test record",
        ]
    lines += [
        "",
        "## Design evidence",
        "Document status: Approved for this synthetic demonstration.",
        f"Requirement source referenced by the control library: {source}",
        f"Control owner record names: {owner}",
    ]
    for i, e in enumerate(elements):
        lines.append(f"- E{i+1}: {_element_fact(c, e, i, scenario)}")
    lines += [
        "",
        "## Operating evidence",
        f"Population/evidence floor recorded in the test contract: {population}",
        "Sample period: 2026-07-01 to 2026-08-31",
    ]
    # Small, control-neutral operating sample; detailed element facts above carry the semantics.
    for i in range(1, 6):
        if scenario == "none" and i > 1:
            break
        status = "verified" if scenario == "full" else "reviewed" if scenario == "partial" else "reference only"
        lines.append(f"- Sample {i}: DEMO-{_slug(cid)}-{i:02d} — {status}; reviewer trace retained.")
    if scenario == "partial":
        lines.append("- Exception note: one mandatory evidence dimension is intentionally absent from this synthetic scenario.")
    if scenario == "none":
        lines.append("- Exception note: substantive operating evidence is intentionally absent from this synthetic scenario.")
    lines += [
        "",
        "## Provenance",
        "This file was generated by the Governance Engine demo evidence generator. It is synthetic fixture data for testing retrieval, assessment, challenge, and dashboard behaviour. It must never be treated as client evidence, regulatory evidence, or an assurance conclusion.",
    ]
    return "\n".join(lines) + "\n"

def generate_pack(destination: str | Path | None = None, scenario: str = "mixed") -> Path:
    if destination is None:
        destination = Path(tempfile.mkdtemp(prefix="governance-engine-demo-") )
    dest = Path(destination)
    dest.mkdir(parents=True, exist_ok=True)
    records = []
    for framework, fn in FRAMEWORK_FILES.items():
        data = yaml.safe_load((CONTRACT_DIR / fn).read_text(encoding="utf-8")) or {}
        for c in data.get("controls", []):
            cid = str(c.get("control_id", "")).strip()
            actual = scenario if scenario in {"full", "partial", "none"} else _scenario_for(f"{framework}/{cid}")
            sub = dest / _slug(framework)
            sub.mkdir(exist_ok=True)
            path = sub / f"{_slug(cid)}_{_slug(c.get('title','control'))}.md"
            path.write_text(_mock_doc(framework, c, actual), encoding="utf-8")
            records.append((framework, cid, actual, path.name))
    (dest / ".demo_manifest.json").write_text(
        __import__('json').dumps({"synthetic": True, "scenario": scenario, "controls": [
            {"framework":fw,"control_id":cid,"scenario":sc,"file":fn} for fw,cid,sc,fn in records
        ]}, indent=2), encoding="utf-8")
    return dest

if __name__ == "__main__":
    print(generate_pack())
